/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.awt.Dimension;
import javax.swing.JToolBar;

/**
 *
 * @author labdessw09
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        tlbMenu.setFloatable (false); 
        this.setSize(new Dimension(300,250));
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(300,250));
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(300,250));
        this.setLocationRelativeTo(null);
//        tlbMenu.addSeparator();
//        tlbMenu.setOrientation(JToolBar.VERTICAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcrGuardar = new javax.swing.JFileChooser();
        dlgCrear = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        dlgVer = new javax.swing.JDialog();
        tlbMenu = new javax.swing.JToolBar();
        btnCrearA = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        btnGuardar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout dlgCrearLayout = new javax.swing.GroupLayout(dlgCrear.getContentPane());
        dlgCrear.getContentPane().setLayout(dlgCrearLayout);
        dlgCrearLayout.setHorizontalGroup(
            dlgCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCrearLayout.createSequentialGroup()
                .addGroup(dlgCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCrearLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnGuardar))
                    .addGroup(dlgCrearLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        dlgCrearLayout.setVerticalGroup(
            dlgCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCrearLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgVerLayout = new javax.swing.GroupLayout(dlgVer.getContentPane());
        dlgVer.getContentPane().setLayout(dlgVerLayout);
        dlgVerLayout.setHorizontalGroup(
            dlgVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgVerLayout.setVerticalGroup(
            dlgVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tlbMenu.setFloatable(false);
        tlbMenu.setForeground(new java.awt.Color(253, 251, 251));
        tlbMenu.setRollover(true);
        tlbMenu.setAutoscrolls(true);

        btnCrearA.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCrearA.setText("Crear archivo");
        btnCrearA.setFocusable(false);
        btnCrearA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbMenu.add(btnCrearA);

        btnVer.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVer.setText("Ver archivo");
        btnVer.setFocusable(false);
        btnVer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbMenu.add(btnVer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearA;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVer;
    private javax.swing.JDialog dlgCrear;
    private javax.swing.JDialog dlgVer;
    private javax.swing.JFileChooser fcrGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar tlbMenu;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
